### ISSUE TITLE
1.17.1 Crash on Database

### ISSUE THREAD

**Issue by vikingexe** [vawser/Warcraft-Universalis#108]
The game crashes while loading database, the music stops and boom, drivers are  updated.

**Comment by vikingexe** [comment]
1.17.1*

**Comment by Xanaa** [comment]
Can you describe this error? In latest version of mod its load good for me

**Comment by vikingexe** [comment]
I've seen you update the mod, i'll try it now

**Comment by vikingexe** [comment]
Okay, so, last update, i checked the mod in eu4 launcher, but when the game starts the custom background put for WE doesn;'t show up, its normal europa universalis 4, i checked the content tab unde rmod and it says its active

**Comment by vikingexe** [comment]
Idk why no mod its  working, the mod is enabled, but when it shows the game its shows the normal eu4, no custom nothing

**Comment by vikingexe** [comment]
I made it work...i bought the game xD

**Comment by Xanaa** [comment]
I see that your problem is solved
