### ISSUE TITLE
Crash with money

### ISSUE THREAD

**Issue by Xanaa** [vawser/Warcraft-Universalis#109]
The game crash if you get some more money (ie. type in console "cash 20000" ). Currently at 33727fbd33acd52ccc1f4ddde7d02a66cf1fd99b.

I think that this error happens becouse of wrong/damaged buildings files.

**Comment by Tivoro** [comment]
Can confirm, crashes at 500+ as Scarlet Crusade.

**Comment by Xanaa** [comment]
![plaakt_500](https://cloud.githubusercontent.com/assets/6237526/17908632/91d0b858-6981-11e6-903f-3e39417211df.jpg)

@Tivoro - So this "500+" exist even in EU4!? Sorry, i cant contain that feeling...
I will look at this error later

**Comment by Xanaa** [comment]
Fixed
