### ISSUE TITLE
Not loading up

### ISSUE THREAD

**Issue by FineAegis** [vawser/Warcraft-Universalis#110]
I have got a problem, I downloaded the mod and followed the instructions but when i load up the game it just loads up default with nothing changed. Am I doing something wrong or is it bugged?

**Comment by vikingexe** [comment]
Same here, with 1.7.0 and with 1.7.1, tried several times, downloaded form github , from steamworkshop with downloader..nothing

**Comment by Xanaa** [comment]
Are you sure that your version of a game is "1.7" not "1.17" ? This Mod is for 1.17.x (I think) for now

**Comment by FineAegis** [comment]
It doesn't have the exclamation mark symbol symbol so I think my game version is allright

**Comment by Xanaa** [comment]
Problem still exist?

**Comment by Sad-Bohemian** [comment]
Yup, I still have the problem. I've got version 1.19.2. I can select it in the launcher, but it loads up the vanilla version, as if it weren't there.

**Comment by vikingexe** [comment]
Ok, so i found out while working on HOI4, why its not loading, and that;'s only for the printed versions i think.Its because the .mod while has a load order scripted.
