### ISSUE TITLE
Heir Names

### ISSUE THREAD

**Issue by gumboLewt** [vawser/Warcraft-Universalis#113]
Some nations don't have first names generated for new heirs. Unsure of cause or full list of countries affected.

Thunder Bluff and Gurubashi are affected, Lordaeron is not.

**Comment by gumboLewt** [comment]
It's missing monarch_names in the country files.  Will take care of it

**Comment by Xanaa** [comment]
#112 Fix something maybe? Close this?

**Comment by gumboLewt** [comment]
Fixed
