### ISSUE TITLE
Areas not present in WoW but existing in Lore

### ISSUE THREAD

**Issue by Xanaa** [vawser/Warcraft-Universalis#44]
Hi, this issue is for areas and provinces that existed in lore but was not implemented in World of Warcraft. I thing that we can add them for better imagination of this Blizzards world.
If you have any sugestion or simply approve this task - write here.
Here you are a list of Areas:
- [x] Zul'Aman / Amani lands behind eastern mountains of Ghostlands
- [ ] Northeron - place where still are living High Elves, Prestor's Estate is here - North of Hearthglen
- [x] Kul Tiras - Human Kingdom near Tol Barad
- [ ] Kezan - the most industrialised island
- [x] Zandalar - with somes provinces like Zuldazar and Mount Mugamba, who's very important for the Trolls

Here you are a list of provinces:
- [ ] Hasic - Port town from warcraft books, I propose to locate them to the south of Scarlet Enclave
- [x] Zul'Dare - Troll islad in Baradin channel
- [x] Frostmane Caves - in entire Mountains of western Dun Morogh
- [ ] Isle of Dread - Island off the west coast of Feralas, sinks after cataclysm.
- [x] The Plunder Isle - main base of the Bloodsail
- [ ] Tel'Abim - FOR BANANAS!!!

Please dont close this even after all things done.
Thx for help in this:
- Blanchard33
- Menekoum

**Comment by Blanchard33** [comment]
I added some concept images I found for a Zul'Aman zone. They are in the 00_sources folder. I hope it helps.

**Comment by Xanaa** [comment]
Zul'Aman done in 3350337145f774534166619e8b32edbe30c4d3e7

**Comment by Menekoum** [comment]
Hi, to complete this list, i've some sugestions:
-Kezan, the most industrialised island
-Zandalar, with somes provinces like Zuldazar and Mount Mugamba, who's very important for the Trolls
-The Plunder Isle, main base of the Bloodsail
-Tel'Abim with his famous Bananas

**Comment by Xanaa** [comment]
Thx @Menekoum , list updated
