### ISSUE TITLE
Localisation - French

### ISSUE THREAD

**Issue by Xanaa** [vawser/Warcraft-Universalis#50]
We need to translate some of our mod files to french. Any volunteers?

**Comment by Menekoum** [comment]
Hi, I'm french and volunteer for translate this mod, it will take time but i can do it.
I don't know how to use GitHub so if you can explain me how to give you my files when done please.

Ps: Booty Bay is missing on the provinces.bmp

**Comment by Xanaa** [comment]
The best way to use github is:
1. Download Github for windows
2. Clone this repository to your account and computer
3. Do what you want to do in translation
4. Send commit to your private repo
5. Create a pull request with descripction to this repo

It isn't really hard, try (in worst, just do it again) and have fun!
