### ISSUE TITLE
Plan for Estates

### ISSUE THREAD

**Issue by vawser** [vawser/Warcraft-Universalis#56]
Here is my rudimentry plan for the estates:

For all civilized countries (so most of the Alliance and some of the Horde)
- Nobility: represents the nobles of the realm
- Merchants: represents the traders of the realm
- Commoners: represents the zeitgeist of the common person

For the tribals (all of the lesser creatures, like murlocs)
- Tribes: represents the tribes that would make up the full nation; allows for interesting interactions

For any nation linked to the Legion:
- The Legion: represents the influence the Legion has over the nation; allows for interesting interactions

For any nation linked to the Old Gods
- The Old Gods: represents the influence of a Old God; allows for interesting interactions

For the Dragonflights
- Dragonflight Cults: represents the influence of the cults on the nation; allows for interesting interactions

Please add some more ideas for groups in the lore that could be represented as estates.

**Comment by Xanaa** [comment]
Maybe something like:
-Lich King
-Titans
-Old gods
for Vrykuls?

**Comment by Xanaa** [comment]
Or
-Demigods (Agamaggan)
-Lich King
for quilboars?

**Comment by Xanaa** [comment]
Estates mainly done. Some minor countries need still fix
