### ISSUE TITLE
Map Commits

### ISSUE THREAD

**Issue by vawser** [vawser/Warcraft-Universalis#66]
This is more of a notice rather than an issue. To help prevent the overlap of map work, it would be best if we take it in turns to commit the map files. 

So, for example I am currently re-doing the heightmap. Since the provinces.bmp needs to be adjusted to follow the new heightmap, any other commits containing provinces.bmp will cause a conflict, and since Git isn't magic the only way to resolve it is to discard one of the files, or manually copy the changes over. Since this isn't very feasible, I thought it best that we state when we are working on the map, so others know not to work on the same files. 

Once you are done, simply edit your comment.

**Comment by vawser** [comment]
2016-02-05

I am working on the heightmap and will be editing the following files:
- heightmap.bmp
- provinces.bmp
- rivers.bmp
- terrain.bmp
- world_normal.bmp
- positions.txt

**Comment by Xanaa** [comment]
2016-02-05

Eeem... so i will work on files in history folder now

**Comment by vawser** [comment]
Just a note. Please don't change the provinces.bmp for a few days. I'm working on reshaping the provinces and filling out areas without enough density, so any province changes would be hard to intergrate.

**Comment by Xanaa** [comment]
No one cares about it too!
